// Generated by scripts/generate_power2_product_identity.py.
// Edit the Power product pointer and regenerate. Intake state is intentionally
// not embedded; trusted repository CI remains authoritative.

enum Power2ProductIdentity {
    static let stackID = "power-text-iphone-2.0.0-rc.2"
    static let measurementStackPath = "products/power/stacks/power-text-iphone-2.0.0-rc.2/manifest.json"
    static let measurementStackSHA256 = "77a8a6b12c9008e9680d8cbfd41a867b4873680a9745172bee4e108f445b47b7"
    static let runnerComponentsManifestPath = "products/power/runner-certificates/evidence/83ecb818-e1f7-4118-80c9-1df9e6fbe8fe/runner-component-manifest.json"
    static let runnerComponentsManifestSHA256 = "ac490be49347ccf2fe6931aa4327921def04b664563afcec4e2809b201cffb1b"
}
